### ISSUE TITLE
第一个步骤

### ISSUE THREAD

**Issue by Gaojinxiao** [SeuTao/TGS-Salt-Identification-Challenge-2018-_4th_place_solution#7]
打扰你了
save the train mask images to disk

python prepare_data.py 这一个步骤的意义是什么 谢谢啦

**Comment by luojiashenyu** [comment]
字面上的理解，保存要训练的掩膜图片到本地磁盘。
这个脚本的名字意思是数据预处理。



---原始邮件---
发件人: "Gaojinxiao"<notifications@github.com&gt;
发送时间: 2020年2月21日(周五) 中午12:12
收件人: "SeuTao/TGS-Salt-Identification-Challenge-2018-_4th_place_solution"<TGS-Salt-Identification-Challenge-2018-_4th_place_solution@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [SeuTao/TGS-Salt-Identification-Challenge-2018-_4th_place_solution] 第一个步骤 (#7)



打扰你了
 save the train mask images to disk
 
python prepare_data.py 这一个步骤的意义是什么 谢谢啦
