### ISSUE TITLE
TypeError: expected Long (got Bool)

### ISSUE THREAD

**Issue by Gaojinxiao** [SeuTao/TGS-Salt-Identification-Challenge-2018-_4th_place_solution#8]
在训练单模型的时候 现实class_lbls = self.to_var(torch.LongTensor(is_empty))中的TypeError 这个该如何解决 我用的是pytorch1.4版本 是版本的问题的吗 谢谢拉

**Comment by luojiashenyu** [comment]
这个我也没认真跑过。疫情隔离在家，手头也没电脑。爱莫能助～～问问其他大牛吧😄我建议你设断点调试下



---Original---

**Comment by Gaojinxiao** [comment]
这个问题解决了 应该是版本兼容的问题 改称torch.LongTensor(is_empty.long())可以解决 但是下面又有坑了 哈哈哈 谢谢啦
